---
# tasks file for rpm_installer
#  all tasks must be started with name
- name: Download from the source url
  # calling get_url built-in module to download RPM from the insecure https site.
  # Document: https://docs.ansible.com/ansible/devel/modules/get_url_module.html
  get_url:
    url: "{{ content_host }}/pub/{{ rpm_filename }}"
    dest: "/tmp/{{ rpm_filename }}"
    mode: 0644
    validate_certs: no

- name: Install the download file
  # calling yum built-in module to install downloaded RPM
  # Document: https://docs.ansible.com/ansible/latest/modules/yum_module.html
  yum:
    name: "/tmp/{{ rpm_filename }}"
    state: present

- name: Clean up the downloaded file
  # calling file built-in module to remove downloaded RPM file.
  # Document: https://docs.ansible.com/ansible/2.5/modules/file_module.html
  file:
    name: "/tmp/{{ rpm_filename }}"
    state: absent


